Add changelog and CI release workflow to parse changelog into GitHub Release
* Add initial changelog

* Add changelog check to release CI workflow.

* Add release step to generate changelog for GitHub release page

* Update contributing section in readme.md

* Update readme with information on documentation

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,6 +6,7 @@ jobs:
   release:
     runs-on: ubuntu-latest
     steps:
+    - uses: actions/checkout@v2
     - name: Extract branch name
       shell: bash
       run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
@@ -23,6 +24,70 @@ jobs:
         echo "::set-output name=major::$(echo $MAJOR)"
         echo "::set-output name=minor::$(echo $MINOR)"
         echo "::set-output name=patch::$(echo $PATCH)"
+    - name: Generate release date
+      id: generate_release_date
+      shell: bash
+      run: |
+        RELEASE_DATE=$(TZ=UTC date '+%Y-%m-%d')
+        echo "::set-output name=release_date::$(echo $RELEASE_DATE)"
+    - name: Validate changelog exists
+      shell: bash
+      run: |
+        VERSION=${{ steps.branch_version.outputs.major }}.${{ steps.branch_version.outputs.minor }}.${{ steps.branch_version.outputs.patch }}
+        RELEASE_DATE=${{ steps.generate_release_date.outputs.release_date }}
+        SEARCH_STRING="## \[$VERSION] - $RELEASE_DATE"
+
+        if [ ! -f changelog.md ]; then
+            echo "Could not find changelog.md - please ensure it is in repo root directory!"
+            exit 1
+        fi
+
+        if grep -Fq "$SEARCH_STRING" changelog.md; then
+          echo "Found valid changelog entry for version $VERSION on release date $RELEASE_DATE"
+        else
+          echo "Could not find changelog entry for version $VERSION on release date $RELEASE_DATE"
+          exit 1
+        fi
+    - name: Generate release changelog
+      id: generate_release_changelog
+      shell: bash
+      run: |
+        BEGIN_DELIMETER_REGEXP='\#\# \\\[${{ steps.branch_version.outputs.major }}\.${{ steps.branch_version.outputs.minor }}\.${{ steps.branch_version.outputs.patch }}] - ${{ steps.generate_release_date.outputs.release_date }}'
+        END_DELIMETER_REGEXP='\#\# \\\[[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+] - [[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}'
+        FOUND_FIRST_DELIMETER=0
+        FOUND_FIRST_LINE=0
+        CHANGELOG=""
+        NEWLINE='%0A'
+        while IFS="" read -r p || [ -n "$p" ]
+        do
+          echo "Checking line ${p}"
+          if [[ $p =~ $BEGIN_DELIMETER_REGEXP ]]; then
+            echo "Found first delimeter"
+            FOUND_FIRST_DELIMETER=1
+            continue
+          fi
+          if [[ $FOUND_FIRST_DELIMETER == 0 ]]; then
+            echo "Did not find first delimeter - skipping line"
+            continue
+          fi
+          if [[ $p =~ $END_DELIMETER_REGEXP ]]; then
+            echo "Found last delimeter - stopping parse"
+            break
+          fi
+          if [[ $FOUND_FIRST_LINE == 0 && -z "$p" ]]; then
+            echo "Found blank line but not first line with text - skipping line"
+            continue
+          fi
+          if [[ $FOUND_FIRST_LINE == 0 ]]; then
+            echo "Found first line of text"
+            FOUND_FIRST_LINE=1
+          fi
+          echo "Adding line to CHANGELOG: ${p}"
+          CHANGELOG="${CHANGELOG}${p}${NEWLINE}"
+        done < changelog.md
+        echo "Changelog:"
+        echo "$CHANGELOG"
+        echo "::set-output name=changelog::$(echo $CHANGELOG)"
     - name: Download workflow artifact
       uses: dawidd6/action-download-artifact@v2.7.0
       with:
@@ -41,6 +106,7 @@ jobs:
         release_name: Release v${{ steps.branch_version.outputs.major }}.${{ steps.branch_version.outputs.minor }}.${{ steps.branch_version.outputs.patch }}
         draft: false
         prerelease: false
+        body: ${{ steps.generate_release_changelog.outputs.changelog }}
     - name: Upload Release Asset
       uses: actions/upload-release-asset@v1.0.2
       env:
